version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  path-filtering: circleci/path-filtering@0.1.2
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.14.0'
      - run: node --version
      - run: yarn
      - aws-cli/setup
      - eb/setup
      - run:
            name: "build job"
            command: |
              echo "this is the build job"
      - run:
            name: Back-End Install
            command: |
              npm run backend:install
      - run:
            name: Back-End Build
            command: |
              npm run backend:build
      - run:
            name: Back-End Deploy
            command: |
              npm run backend:deploy
      - run:
            name: Front-End Install
            command: |
              npm run frontend:install
      - run:
            name: Front-End Build
            command: |
              npm run frontend:build
      - run:
            name: Front-End Deploy
            command: |
              npm run frontend:deploy
      - run:
            name: Signature
            command: |
              echo "Abdel Moumen Abdel Raouf Abdullah [Ali Al-Masry]"
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-deploy:
          filters:
            branches:
             only: main
      - test
