version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: ""
    steps:
      - node/install
      - checkout
      - run:
          name: hello
          command: |
            echo "Abdel Moumen Abdel Raouf Abdullah"
